apiVersion: apps/v1
kind: Deployment
metadata:
  name: adventureworks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adventureworks
  template:
    metadata:
      labels:
        app: adventureworks
    spec:
      initContainers:
      - name: download-bak-file
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - |
            wget --no-verbose --show-progress --https-only \
              --output-document=AdventureWorksLT2022.bak \
              https://github.com/Microsoft/sql-server-samples/releases/download/adventureworks/AdventureWorksLT2022.bak
        volumeMounts:
        - name: db-volume
          mountPath: /var/opt/mssql/data
      containers:
      - name: database
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "P@ssword!"
        volumeMounts:
        - name: db-volume
          mountPath: /var/opt/mssql/data
      volumes:
      - name: db-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: adventureworks-service
spec:
  selector:
    app: adventureworks
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
    nodePort: 31433
  type: NodePort
