apiVersion: v1
kind: Pod
metadata:
  name: adventureworks-db
spec:
  containers:
  - name: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
    - containerPort: 1433
      hostPort: 31433 # k9sで動かす時はコメントアウトしてsvc.yamlをapplyする
    env:
    - name: ACCEPT_EULA
      value: "Y"
    - name: SA_PASSWORD
      value: "P@ssword!"
    resources:
      limits:
        memory: "4Gi"
      requests:
        memory: "2Gi"
    volumeMounts:
    - name: db-volume
      mountPath: /var/opt/mssql/data
  initContainers:
  - name: download-bak-file
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
      - |
        # 所有者を UID=10001, GID=10001 (mssql) に変更
        chown -R 10001:10001 /var/opt/mssql/data && \
        apk add --no-cache wget && \
        wget --no-verbose --https-only \
          --output-document=/var/opt/mssql/data/AdventureWorksLT2022.bak \
          https://github.com/Microsoft/sql-server-samples/releases/download/adventureworks/AdventureWorksLT2022.bak
    volumeMounts:
    - name: db-volume
      mountPath: /var/opt/mssql/data
  volumes:
  - name: db-volume
    emptyDir: {}
