apiVersion: v1
kind: Pod
metadata:
  name: adventureworks-db
  spec:
    initContainers:
    - name: download-bak-file
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          wget --no-verbose --show-progress --https-only \
            --output-document=AdventureWorksLT2022.bak \
            https://github.com/Microsoft/sql-server-samples/releases/download/adventureworks/AdventureWorksLT2022.bak
      volumeMounts:
      - name: db-volume
        mountPath: /var/opt/mssql/data
    containers:
    - name: database
      image: mcr.microsoft.com/mssql/server:2022-latest
      ports:
      - containerPort: 1433
        hostPort: 1433 # k9sで動かす時はコメントアウトしてsvc.yamlをapplyする
      env:
      - name: ACCEPT_EULA
        value: "Y"
      - name: SA_PASSWORD
        value: "P@ssword!"
      volumeMounts:
      - name: db-volume
        mountPath: /var/opt/mssql/data
    volumes:
    - name: db-volume
      emptyDir: {}
