services:
  database:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: neko3cs-database
    ports:
      - 1433:1433
    volumes:
      - type: bind
        source: $PWD
        target: /data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssword!
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools18/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "P@ssword!",
          "-Q",
          "SELECT 1",
          "-C",
        ]
      interval: 5s
      timeout: 3s
      retries: 10
