version: '3'
services:
  database:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: neko3cs-database
    ports:
      - 1433:1433
    volumes:
      - type: bind
        source: $PWD
        target: /data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssword!
